### ISSUE TITLE
2010 Historical Data Error

### ISSUE THREAD

**Issue by ciacci1234** [Anti-Gerrymandering/visualization#34] opened 2017-05-07 16:35 UTC
Every other year seems to be working properly, except for 2010. which encounters an undefined error that I've attached below.

![2010-error](https://cloud.githubusercontent.com/assets/14255433/25782949/96882c2c-3321-11e7-9ebd-d124cf56597e.png)

**Comment by jonmast** [comment] 2017-08-08 22:49
@ciacci1234 I am unable to duplicate this, so closing it for now. I think I vaguely remember having worked on it at some point, I probably forgot to close the issue. Please reopen if you are still seeing it.

**Comment by ciacci1234** [comment] 2017-08-09 13:42
@jonmast I'm still encountering the issue on my end :hushed: Here is what I did to recreate the bug:

1. Refresh the page. 
2. Click Around on Districts for 2015 in "US. House Districts" to display corresponding district info
3. Click on "PA Senate Districts" Tab
4. Click on 2013 or another year that's not 2010. 
5. Click Around different districts to display corresponding district info
6. Click on 2010
7. Click Districts and instead of displaying corresponding district info, map continues to display info from previously clicked district. And in the console, the above error shows up

This was done in Chrome, but I also encountered the error using Firefox. I'm currently using a Mac running Yosemite version 10.10.5. You are on Linux I believe? I suppose this could be the issue, but I think something simpler is going on

Did you make changes that are not yet deployed which fix this issue?

**Comment by ciacci1234** [comment] 2017-08-09 13:51
@jonmast I asked a coworker (who also is on a Mac, but a more updated version), to recreate the bug, and he encountered the issue as well 👌

**Comment by jonmast** [comment] 2017-08-09 13:58
@ciacci1234 Thanks for the recreation steps, I'm seeing it as well. I just wasn't diligent enough in my recreation attempts, sorry about that.

**Comment by ciacci1234** [comment] 2017-08-09 14:00
@jonmast No prob! Glad you see what I'm seeing 🆗  I'll remember to put recreation steps for any future bugs I discover 👍

**Comment by jonmast** [comment] 2017-08-12 22:12
I dug into this a bit more, and it appears the issue is that the 2010 geojson files don't have a GEOID property like the others. They have a GEO_ID property, but this is actually what is referred to as AFFGEOID in the other files. While there doesn't seem to be a field that corresponds exactly with what the other files have, all the necessary data is there so it should be possible to add the property with a simple script.

**Comment by ciacci1234** [comment] 2017-08-12 22:31
Do you mean adding the GEOID property to the 2010 file? Wouldn't it be more straightforward to access the 2010 data using the GEO_ID key?

**Comment by jonmast** [comment] 2017-08-12 23:04
Hmm, I guess that would be another option that might be easier. In general though, I prefer having data in a consistent format whenever possible, adding special cases to deal with inconsistencies tends to lead to headaches.

At any rate, it occurred to me that a simple find and replace regex on the files would be sufficient, see PR #39

**Closed as completed** 2017-08-13 23:34 UTC
Labels: bug, mid-priority
